#
# .github/workflows/build-on-linux.yml
#
# Copyright 2021 Jens A. Koch.
# SPDX-License-Identifier: AGPL-3.0-only
# This file is part of https://github.com/jakoch/hdoc.
#

name: "Build"

on:  
  push:
  pull_request:

jobs:

# ---------------------------------------------------------------------------------------

  build:

# ---------------------------------------------------------------------------------------
    
    name: "Build"
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: 🔽 Install Python and Ninja
      run: sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build
      
    - name: 🔽 Install Meson
      run: pip3 install meson
